package com.testng.exception;

import org.testng.annotations.Test;

public class TestException {

	@Test
	public void Test1() {
		System.out.println("This is Test1 Of ");

	}

	@Test
	public void Test2() {
		System.out.println("This is Test2 Of ");

	}

}
